# CI Build

name: CI Build

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs: 
      gradleArgs: 
        description: 'Additional Gradle parameters'     
        required: false
        default: '' 
        type: string
      buildDockerImage:
        description: 'Build Docker Image'     
        required: false
        default: "true"
        type: boolean
      uploadHelmChart:
        description: 'Upload Helm Chart'     
        required: false
        default: "false"
        type: boolean

jobs:
  build:
    uses: zometer/github-actions/.github/workflows/build-gradle-docker-helm.yml@main 
    with: 
      gradleArgs: ${{ github.event.inputs.gradleArgs }}
      buildDockerImage: ${{ github.event.inputs.buildDockerImage }}
      uploadHelmChart: ${{ github.event.inputs.uploadHelmChart }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

