# Workflow for building a new release, incrementing the version, and 
# deploying the helm chart to the github chart repo. 

name: Sandbox

on:
  workflow_dispatch:
    inputs:
      gradleArgs:
        description: 'Additional Gradle parameters'
        required: false
        default: ''
        type: string
      helmChartRepo: 
        description: 'Helm Chart Repository'
        required: true
        default: 'zometer/helm-charts'
        type: string
      helmChartRepoBranch: 
        description: 'Helm chart index branch'
        required: true
        default: 'gh-pages'
        type: string
        
jobs:
  build:
    uses: zometer/github-actions/.github/workflows/build-gradle-docker-helm.yml@main 
    with: 
      gradleTasks: build 
      gradleArgs: -Prelease.useAutomaticVersion=true ${{ github.event.inputs.gradleArgs }}
      buildDockerImage: true
      uploadHelmChart: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
  
  troubleshoot:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: WTF 
        run: | 
          echo "${{ toJSON(needs.build) }}"

  deploy-helm-chart:
    needs: build
    uses: zometer/github-actions/.github/workflows/push-helm-chart.yml@main
    with: 
      helmChartRepo: ${{ github.event.inputs.helmChartRepo }} 
      helmChartRepoBranch: ${{ github.event.inputs.helmChartRepoBranch }}
      artifactName: helm-chart
      chartName: ${{ needs.build.outputs.artifact }}
      chartVersion: ${{ needs.build.outputs.version }}      
    secrets: 
      githubToken: ${{ secrets.HELM_CHARTS_REPO_TOKEN }}
